# Site settings
title: Blog n' Stuff
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Blah blah blah
baseurl: "" # the subpath of your site, e.g. /blog/
url: "jbwinters.github.io" # the base hostname & protocol for your site
github_username:  jbwinters

# Build settings
markdown: kramdown
